api_platform:
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
        # config/packages/api_platform.yaml

  formats:
    multipart: ['multipart/form-data']
    jsonld: ['application/ld+json']
